### ISSUE TITLE
Installation error: error in cuda_runtime_api.h

### ISSUE THREAD

**Issue by tzodge** [StanfordVL/MinkowskiEngine#138]
Hi, 
I am trying to install MinkowskiEngine with conda. 
My settings are
Python 3.7.7
GCC 7.3.0
torch 1.5.0
Cuda 10.1.243

I am getting errors like this 

/usr/local/cuda/include/cuda_runtime_api.h:9185:55: note: suggested alternative: ‘cudaGraphCreate’
 extern __host__ cudaError_t CUDARTAPI cudaGraphLaunch(cudaGraphExec_t graphExec, cudaStream_t stream);
                                                       ^~~~~~~~~~~~~~~
                                                       cudaGraphCreate
/usr/local/cuda/include/cuda_runtime_api.h:9185:95: error: expected primary-expression before ‘stream’
 extern __host__ cudaError_t CUDARTAPI cudaGraphLaunch(cudaGraphExec_t graphExec, cudaStream_t stream);

followed by 
Makefile:162: recipe for target 'objs/coords_key.o' failed
make: *** [objs/coords_key.o] Error 1
Makefile:162: recipe for target 'objs/union.o' failed
make: *** [objs/union.o] Error 1
Makefile:162: recipe for target 'objs/coords_manager.o' failed
make: *** [objs/coords_manager.o] Error 1
Makefile:162: recipe for target 'objs/pooling_avg.o' failed
make: *** [objs/pooling_avg.o] Error 1
Makefile:162: recipe for target 'objs/pooling_max.o' failed
make: *** [objs/pooling_max.o] Error 1
Makefile:162: recipe for target 'objs/convolution_transpose.o' failed
make: *** [objs/convolution_transpose.o] Error 1
Makefile:162: recipe for target 'objs/pooling_global_max.o' failed
make: *** [objs/pooling_global_max.o] Error 1
Makefile:162: recipe for target 'objs/pooling_transpose.o' failed
make: *** [objs/pooling_transpose.o] Error 1
Makefile:162: recipe for target 'objs/broadcast.o' failed
make: *** [objs/broadcast.o] Error 1
Makefile:162: recipe for target 'objs/pooling_global_avg.o' failed
make: *** [objs/pooling_global_avg.o] Error 1
Makefile:162: recipe for target 'objs/quantization.o' failed
make: *** [objs/quantization.o] Error 1
Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    run_command(*compile_args)
  File "setup.py", line 90, in run_command
    subprocess.check_call(args)
  File "/home/biorobotics/anaconda3/envs/FCGF3/lib/python3.7/subprocess.py", line 363, in check_call

The complete error log is too long so it can be found in this attached google [doc file](https://docs.google.com/document/d/1bB_qyK1n20-pw43k7nZdPYLGLUgGRaZ-yHZAJhkVTFc/edit?usp=sharing)

Any help is appreciated. 
Thanks in advance :)

**Comment by chrischoy** [comment]
Looks like you are using a different CUDA version for compilation.

There's a solution for this on the cuda forum https://forums.developer.nvidia.com/t/cudnn-test-did-not-pass/54675/23

**Comment by tzodge** [comment]
Hey chris,
Thanks for the quick reply. 
Turns out there are some issues with my cudnn installation.

I'll repair that installation.

Thanks,
Tejas
