### ISSUE TITLE
RuntimeError:  an illegal memory access was encountered at src/convolution.cu:259 device number specification and assertion

### ISSUE THREAD

**Issue by GaoQiyu** [StanfordVL/MinkowskiEngine#40]
I can run my code with GTX1060
but it doesn't works with Tesla P100 on server 
Ant output:

Traceback_ (most recent call last):
  File "train.py", line 135, in <module>
        trainer.train(epoch)

  File "train.py", line 56, in train
    output_sparse = self.model(point)

  File "/home/gaoqiyu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
        result = self.forward(*input, **kwargs)

  File "/home/gaoqiyu/PointCloudSeg_Minkowski/model/minkunet.py", line 122, in forward
        out = self.conv0p1s1(x)

  File "/home/gaoqiyu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
        result = self.forward(*input, **kwargs)

  File "/home/gaoqiyu/PointCloudSeg_Minkowski/MinkowskiEngine/MinkowskiConvolution.py", line 269, in forward
        out_coords_key, input.coords_man)

  File "/home/gaoqiyu/PointCloudSeg_Minkowski/MinkowskiEngine/MinkowskiConvolution.py", line 91, in forward
        ctx.coords_man.CPPCoordsManager)
RuntimeError:  an illegal memory access was encountered at src/convolution.cu:259

**Comment by chrischoy** [comment]
Hmm could you post the engine version, cuda version, nvcc version?

I confirmed it worked on most Pascal architecture chips, but not the P100. I’ll check.

**Comment by GaoQiyu** [comment]
System:    Host: C249-SYS-7048GR-TR Kernel: 4.15.0-54-generic x86_64 bits: 64 Console: tty 3
           Distro: Ubuntu 18.04.2 LTS
Machine:   Device: kvm System: Supermicro product: SYS-7048GR-TR v: 0123456789 serial: N/A
           Mobo: Supermicro model: X10DRG-Q v: 1.10 serial: N/A
           UEFI [Legacy]: American Megatrends v: 2.0b date: 07/26/2017
CPU(s):    2 8 core Intel Xeon E5-2620 v4s (-MT-MCP-SMP-) cache: 40960 KB
           clock speeds: max: 3000 MHz 1: 1200 MHz 2: 1206 MHz 3: 1347 MHz 4: 1209 MHz 5: 1741 MHz 6: 1201 MHz
           7: 1200 MHz 8: 1271 MHz 9: 1292 MHz 10: 1200 MHz 11: 1202 MHz 12: 1204 MHz 13: 1200 MHz 14: 1204 MHz
           15: 1200 MHz 16: 1200 MHz 17: 1200 MHz 18: 1206 MHz 19: 1218 MHz 20: 1246 MHz 21: 1295 MHz
           22: 1202 MHz 23: 1200 MHz 24: 1843 MHz 25: 1825 MHz 26: 1200 MHz 27: 1200 MHz 28: 1202 MHz
           29: 1200 MHz 30: 1211 MHz 31: 1200 MHz 32: 1200 MHz
Graphics:  Card-1: NVIDIA GM206GL [Quadro M2000]
           Card-2: NVIDIA GP100GL [Tesla P100 PCIe 16GB]
           Card-3: ASPEED ASPEED Graphics Family
           Card-4: NVIDIA GP100GL [Tesla P100 PCIe 16GB]
           Display Server: N/A drivers: nvidia (unloaded: fbdev,vesa) FAILED: modesetting,nouveau
           tty size: 160x49 Advanced Data: N/A out of X
Audio:     Card-1 NVIDIA Device 0fba driver: snd_hda_intel Sound: ALSA v: k4.15.0-54-generic
           Card-2 Intel C610/X99 series HD Audio Controller driver: snd_hda_intel
Network:   Card-1: Intel I350 Gigabit Network Connection driver: igb
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: ac:1f:6b:81:63:7c
           Card-2: Intel I350 Gigabit Network Connection driver: igb
           IF: eno2 state: up speed: 1000 Mbps duplex: full mac: ac:1f:6b:81:63:7d
Drives:    HDD Total Size: 6501.3GB (28.0% used)
           ID-1: /dev/sda model: Samsung_SSD_860 size: 500.1GB
           ID-2: /dev/sdb model: WDC_WD2005FBYZ size: 2000.4GB
           ID-3: /dev/sdc model: WDC_WD2005FBYZ size: 2000.4GB
           ID-4: /dev/sdd model: WDC_WD1003FZEX size: 1000.2GB
           ID-5: /dev/sde model: WDC_WD1003FZEX size: 1000.2GB
Partition: ID-1: / size: 94G used: 22G (25%) fs: ext4 dev: /dev/sda3
           ID-2: /home size: 303G used: 100G (35%) fs: ext4 dev: /dev/sda5
           ID-3: /boot size: 945M used: 207M (24%) fs: ext4 dev: /dev/sda1
           ID-4: swap-1 size: 65.53GB used: 1.61GB (2%) fs: swap dev: /dev/sda6
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 23.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 519 Uptime: 113 days Memory: 4992.7/128808.8MB Init: systemd runlevel: 5
           Client: Shell (bash) inxi: 2.3.56

**Comment by chrischoy** [comment]
I checked it works on K40, K80, GTX1060, GTX1080Ti, GTX2080Ti, Titan X, Titan XP, Titan RTX, V100.

**Comment by GaoQiyu** [comment]
ok I fix it
just set 
`self.device = torch.device("cuda:0")`

**Comment by chrischoy** [comment]
Hmm interesting. I’ve always specified this before so I didn’t encounter this, but adding some assertion check to prevent this would be a good idea.

**Comment by GaoQiyu** [comment]
I find when use the first gpu it always work, but if use other gpu, it seems the program will also use the first gpu, and the one which is specified. so this is the real error. I don't know whether it is my code mistake.（Very likely) I will check it.
sorry to bother

**Comment by chrischoy** [comment]
I always use `export CUDA_VISIBLE_DEVICES=2; python main.py .....` to run programs on a server. I haven’t checked the multi-gpu setup for newer pytorch version, so it is possible that this is not working well with newer pytorch.

**Comment by chrischoy** [comment]
For pytorch v1.3.1, we found out that the asynchronous memory allocation in pytorch doesn't always emit the error in place and propagates the error back to the engine.

To verify this is not the error in the engine, we placed `CUDA_CHECK(cudaDeviceSynchronize())` before any CUDA calls inside `convolution.cu`.

We found out that when OOM were to happen, we get this error `illegal memory access` on the `cudaDeviceSynchronize()` call. I suspect that this is linked with asynchronous device malloc failure that lead to accessing invalid pointer on device which is hidden until we force the device synchronization.

This requires further investigation in side the pytorch as well, but for now, I can assure you that there is no memory leakage, invalid pointer access error in the Minkowski Engine.

**Comment by asurada404** [comment]
When I use `export CUDA_VISIBLE_DEVICES=1`, I can't set Tensor's device by `.to` method.
For example:
```
$ export CUDA_VISIBLE_DEVICES=1
$ python
```
But I got an error:
```
>>> import torch
>>> a = torch.Tensor(1).to("cuda:0")
>>> a = torch.Tensor(1).to("cuda:1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: invalid device ordinal
```

**Comment by GaoQiyu** [comment]
> When I use `export CUDA_VISIBLE_DEVICES=1`, I can't set Tensor's device by `.to` method.
> For example:
> 
> ```
> $ export CUDA_VISIBLE_DEVICES=1
> $ python
> ```
> 
> But I got an error:
> 
> ```
> >>> import torch
> >>> a = torch.Tensor(1).to("cuda:0")
> >>> a = torch.Tensor(1).to("cuda:1")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: CUDA error: invalid device ordinal
> ```

when you set CUDA_VISIBLE_DEVICES=1, the only GPU your code can get is the second gpu in your system. So I think if you set "a = torch.Tensor(1).to("cuda:0")", it will be ok.
but you can't set "a = torch.Tensor(1).to("cuda:1")" because the code can't see another gpu
