### ISSUE TITLE
RuntimeError: invalid device function at src/convolution.cu:283

### ISSUE THREAD

**Issue by peiyunh** [StanfordVL/MinkowskiEngine#73]
I run into segmentation fault (core dumped) when I do `python -m examples.example`. I installed the library through conda (also tried pip). The environment is Ubuntu 18.04.3 LTS and CUDA 10.0. The GPU is RTX 2080 Ti. 

```
(py3-mink) peiyunh@voxel:~/work/MinkowskiEngine (master=) $ python -m examples.example                                             
ExampleNetwork(                                                                                                                    
  (net): Sequential(                                                                                                               
    (0): MinkowskiConvolution(in=3, out=64, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3], stride=[2, 2], dilation=[1, 1])  
    (1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)                                    
    (2): MinkowskiReLU()                                                                                                           
    (3): MinkowskiConvolution(in=64, out=128, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3], stride=[2, 2], dilation=[1, 1])
    (4): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)                                   
    (5): MinkowskiReLU()                                                                                                           
    (6): MinkowskiGlobalPooling(average=True)                                                                                      
    (7): MinkowskiLinear(in_features=128, out_features=5, bias=True)                                                               
  )                                                                                                                                
)                                                                                                                                  
Traceback (most recent call last):                                                                                                 
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main                            
    "__main__", mod_spec)                                                                                                          
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/runpy.py", line 85, in _run_code                                       
    exec(code, run_globals)                                                                                                        
  File "/home/peiyunh/work/MinkowskiEngine/examples/example.py", line 80, in <module>                                              
    output = net(input)                                                                                                            
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__       
    result = self.forward(*input, **kwargs)                                                                                        
  File "/home/peiyunh/work/MinkowskiEngine/examples/example.py", line 56, in forward                                               
    return self.net(x)                                                                                                             
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__       
    result = self.forward(*input, **kwargs)                                                                                        
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward      
    input = module(input)                                                                                                          
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__       
    result = self.forward(*input, **kwargs)                                                                                        
  File "/home/peiyunh/work/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 278, in forward                          
    out_coords_key, input.coords_man)                                                                                              
  File "/home/peiyunh/work/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 93, in forward                           
    ctx.coords_man.CPPCoordsManager)                                                                                               
RuntimeError:  invalid device function at src/convolution.cu:283                                                                   
Segmentation fault (core dumped)                                                                                                   
```

_Originally posted by @peiyunh in https://github.com/StanfordVL/MinkowskiEngine/issues/63#issuecomment-572206712_

**Comment by chrischoy** [comment]
Seems related to this. https://github.com/facebookresearch/detectron2/issues/62

The pytorch wheel does not provide CUDA 10.0 version if you installed with conda, or pip. Try to upgrade your system nvcc to CUDA 10.1 so that pytorch and MinkowskiEngine uses the same CUDA version.

**Comment by peiyunh** [comment]
Thanks for your prompt response. You are exactly right. 

I installed a version of PyTorch that's compiled with CUDA 10.0 and it works now! 

To anyone who prefers not upgrading CUDA 10.0 to 10.1, here is how to install PyTorch that's compiled with CUDA 10.0 through pip: https://github.com/pytorch/pytorch/issues/28321#issuecomment-561406072
